name: Testing

on:
  workflow_dispatch:
    inputs:
      description:
        description: The description of the version
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Python time
        id: calc
        shell: python
        env:
          THE_INPUT: "${{ inputs.description }}"
        run: | 
          import os
          value = os.getenv("THE_INPUT")
          print(value)
          new_value = value.replace("\\n", "\n")
          print(new_value)
          
          os.environ[GITHUB_OUTPUT] = f"out={new_value}"
      - name: Test
        run: echo "${{ steps.calc.outputs.out }}"
