name: Testing

on:
  workflow_dispatch:
    inputs:
      description:
        description: The description of the version
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fix lines in changelog
        id: changelog
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: "${{ inputs.description }}"
          find: "\\n"
          replace: "\n"
      - name: Do the thing
        run: echo "${{ steps.changelog.outputs.value }}"
      - name: Python time
        shell: python
        run: | 
          import os
          print("""${{ steps.changelog.outputs.value }}""")
