name: Testing

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: "Test input"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create output
        id: calc
        shell: python
        env:
          THE_INPUT: "${{ inputs.test_input }}"
        run: |
          import os
          import random
          import string

          value = os.getenv("THE_INPUT")
          print(value)

          delimiter = "".join(random.choice(string.ascii_letters + string.digits) for i in range(30))

          with open(os.environ["GITHUB_OUTPUT"], "w") as out:
              out.write(f"out<<{delimiter}\n{value}\n{delimiter}")
      - name: Read props
        id: props
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: test.properties
          properties: "${{steps.calc.outputs.out}}"
      - name: Test
        env:
          THE_INPUT: "${{ format('{0} {1} {2}', inputs.test_input, steps.calc.outputs.out || 'test' , steps.props.outputs.test_value) }}"
        run: echo $THE_INPUT
